### ISSUE TITLE
The menu overlaps slider

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/tiny-hestia#28]
After update, the menu is overlapping slider - https://secure.helpscout.net/conversation/665819846/169682/?folderId=212385

**Comment by Vishakha-Patel** [comment]
@stefan-cotitosu

**Comment by stefan-cotitosu** [comment]
@Vishakha-Patel Thank you for reporting this. 

Tiny Hestia was made as a blog theme and it should work properly with `Your Latest Posts` option on Homepage Setting. If you choose `A static page` and assign a page as the front page, because Tiny Hestia doesn't have the front page with the sections (Team, Testimonials etc) the menu is still transparent on the front page. This is a bug, because it doesn't inherit Hestia front page template, but it does inherit the menu transparency for the front page.

We are not going to fix this, as this child theme has many issues. Users should be advice to use Hestia, and disable the front page from the Appearance settings.

![hestia-disable-frontpage](https://user-images.githubusercontent.com/26867648/49499629-4d829400-f877-11e8-94e3-498c39b2a5e4.png)
